
DIALOG MAINDIALOG
{

	GROUP
	{
		BORDERSIZE 20,20,20,0; // left, top, right, bottom;
		SCALE_H;

		STATICTEXT INSTRUCTION { SCALE_H; ALIGN_LEFT; }
	}

	GROUP
	{
		BORDERSIZE 20,20,20,20;
		SCALE_H;
		COLUMNS 1;
		ROWS 1;

		GROUP
		{
			BORDERSTYLE BORDER_GROUP_IN;
			BORDERSIZE 20,20,20,20;
			SPACE 0, 10;
			SCALE_H;
			COLUMNS 1;
			ROWS 17;
			CHECKBOX DESTINATION { NAME DESTINATION_STR; SCALE_H; ALIGN_LEFT; }
			CHECKBOX PRETTY { NAME PRETTY_STR; SCALE_H; ALIGN_LEFT; }
			GROUP {
				SPACE 30, 10;
				STATICTEXT { NAME PRECISION_STR; ALIGN_LEFT; }
				EDITNUMBER PRECISION { SIZE 10,0; ALIGN_LEFT; }
			}
			SEPARATOR { SCALE_H; }
			CHECKBOX TRIANGULATE { NAME TRIANGULATE_STR; SCALE_H; ALIGN_LEFT; }
			CHECKBOX PHONG { NAME PHONG_STR; SCALE_H; ALIGN_LEFT; }
			SEPARATOR { SCALE_H; }
			CHECKBOX VERTICES { NAME VERTICES_STR; SCALE_H; ALIGN_LEFT; }
			GROUP {
				COLUMNS 2;
				ROWS 2;
				SPACE 20, 10;
				CHECKBOX NORMALS { NAME NORMALS_STR; ALIGN_LEFT; }
				RADIOGROUP NORMALSELECT
				{
					SPACE 10, 10;
					RADIOGADGET NORMALSFACE { NAME NORMALSFACE_STR; }
					RADIOGADGET NORMALSVERTEX { NAME NORMALSVERTEX_STR; }
				}				

				CHECKBOX UVS { NAME UVS_STR; ALIGN_LEFT; }
				GROUP {
					SPACE 10, 10;
					CHECKBOX FLIPU { NAME FLIPU_STR; ALIGN_LEFT; }
					CHECKBOX FLIPV { NAME FLIPV_STR; ALIGN_LEFT; }
				}
			}
			CHECKBOX FACES { NAME FACES_STR; SCALE_H; ALIGN_LEFT; }
			SEPARATOR { SCALE_H; }
			GROUP {
				COLUMNS 2;
				ROWS 1;
				SPACE 30, 10;
				CHECKBOX BONES { NAME BONES_STR; ALIGN_LEFT; }
				COMBOBOX BONESELECT { ALIGN_LEFT; }
			}
			CHECKBOX WEIGHTS { NAME WEIGHTS_STR; SCALE_H; ALIGN_LEFT; }
			CHECKBOX SKANIM { NAME SKANIM_STR; SCALE_H; ALIGN_LEFT; }
			GROUP {
				COLUMNS 2;
				ROWS 2;
				STATICTEXT INFLUENCESLABEL { NAME INFLUENCES_STR; ALIGN_LEFT; }
				EDITNUMBER INFLUENCES { SIZE 10,0; ALIGN_LEFT; }
				STATICTEXT FPSLABEL { NAME FPS_STR; ALIGN_LEFT; }
				EDITNUMBER FPS { SIZE 30,0; ALIGN_LEFT; }
			}
		}
	}

	GROUP
	{
		BORDERSIZE 20,0,20,20;
		CENTER_H;
		DLGGROUP { OK; CANCEL; }
	}

}